- name: Install K3s Master
  hosts: master
  become: true
  tasks:
    - name: Download and install K3s
      shell: |
        curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--write-kubeconfig-mode=644 --node-taint CriticalAddonsOnly=true:NoExecute" sh -

    - name: Get K3s Node Token
      shell: cat /var/lib/rancher/k3s/server/node-token
      register: k3s_token
      changed_when: false

    - name: Set Token for Workers
      set_fact:
        node_token: "{{ k3s_token.stdout }}"



- name: Install K3s Worker
  hosts: worker
  become: true
  tasks:
    - name: Join Worker to K3s Cluster
      shell: |
        curl -sfL https://get.k3s.io | K3S_URL=https://{{ hostvars['master']['ansible_host'] }}:6443 K3S_TOKEN={{ hostvars['master']['node_token'] }} sh -
